export const SEARCH_RESULTS_START = 'SEARCH_RESULTS_START'
export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS'
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE'

export const DETAILED_INFO = 'DETAILED_INFO'

export const CATALOG_DATA = 'CATALOG_DATA'

export const HEADER_DATA_START = 'HEADER_DATA_START'
export const HEADER_DATA_SUCCESS = 'HEADER_DATA_SUCCESS'
export const HEADER_DATA_FAILURE = 'HEADER_DATA_FAILURE'
export const HEADER_TRAILER = 'HEADER_TRAILER'

export const LOGIN_FORM_OPEN = 'LOGIN_FORM_OPEN'

export const SIGNUP_FORM_OPEN = 'SIGNUP_FORM_OPEN'