export const SEARCH_RESULTS = 'SEARCH_RESULTS'

export const DETAILED_INFO = 'DETAILED_INFO'

export const CATALOG_DATA = 'CATALOG_DATA'

export const HEADER_DATA_START = 'HEADER_DATA_START'
export const HEADER_DATA_SUCCESS = 'HEADER_DATA_SUCCESS'
export const HEADER_DATA_FAILURE = 'HEADER_DATA_FAILURE'
export const HEADER_TRAILER = 'HEADER_TRAILER'