export const SEARCH_RESULTS_START = "SEARCH_RESULTS_START";
export const SEARCH_RESULTS_SUCCESS = "SEARCH_RESULTS_SUCCESS";
export const SEARCH_RESULTS_FAILURE = "SEARCH_RESULTS_FAILURE";

export const DETAILED_INFO_START = "DETAILED_INFO_START";
export const DETAILED_INFO_SUCCESS = "DETAILED_INFO_SUCCESS";
export const DETAILED_INFO_FAILURE = "DETAILED_INFO_FAILURE";

export const CATALOG_DATA_RESPONSE = "CATALOG_DATA_RESPONSE";
export const CATALOG_SEARCH_SELECTOR = "CATALOG_SEARCH_SELECTOR";
export const CATALOG_CURRENT_PAGE = "CATALOG_CURRENT_PAGE";
export const CATALOG_DATA_LENGTH = "CATALOG_CURRENT_PAGE";
export const CATALOG_TOTAL_PAGES = "CATALOG_CURRENT_PAGE";
export const CATALOG_HAS_MORE = "CATALOG_HAS_MORE";

export const HEADER_DATA_START = "HEADER_DATA_START";
export const HEADER_DATA_SUCCESS = "HEADER_DATA_SUCCESS";
export const HEADER_DATA_FAILURE = "HEADER_DATA_FAILURE";
export const HEADER_TRAILER = "HEADER_TRAILER";

export const AUTH_LOGINFORM_OPEN = "AUTH_LOGIN_FORM_OPEN";
export const AUTH_SIGNUPFORM_OPEN = "AUTH_SIGNUP_FORM_OPEN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_GET_PAGE = "AUTH_GET_PAGE";
export const AUTH_USER_PAGE_POST = "AUTH_USER_PAGE_POST";
export const AUTH_USER_PAGE_FETCH = "AUTH_USER_PAGE_FETCH";
export const AUTH_USER_REMOVE_ITEM = "AUTH_USER_REMOVE_ITEM";
